<?php
declare(strict_types=1);
try {
    require __DIR__ . '/app/bootstrap.php';
} catch (Throwable $bootstrapError) {
    error_log('[MORFINITY bootstrap] ' . get_debug_type($bootstrapError) . ': ' . $bootstrapError->getMessage());
    http_response_code(500);
    header('Content-Type: text/html; charset=UTF-8');
    $showDetail = filter_var(getenv('APP_DEBUG') ?: 'false', FILTER_VALIDATE_BOOLEAN)
        && strtolower((string)(getenv('APP_ENV') ?: 'production')) !== 'production';
    $message = $showDetail ? htmlspecialchars($bootstrapError->getMessage(), ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8') : 'The application is temporarily unavailable.';
    echo '<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Server error | MORFINITY</title><body><main><h1>Something went wrong.</h1><p>' . $message . '</p></main></body></html>';
    exit;
}

$path = '/' . trim((string)(parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH) ?: '/'), '/');
$method = $_SERVER['REQUEST_METHOD'] ?? 'GET';

try {
    if ($path === '/' && $method === 'GET') {
        render('home', ['title'=>'More than a brand','products'=>query_all("SELECT p.*,b.name brand_name FROM products p LEFT JOIN brands b ON b.id=p.brand_id WHERE p.status='active' AND p.featured=1 ORDER BY p.created_at DESC LIMIT 6"),'brands'=>query_all("SELECT * FROM brands WHERE status='active' AND featured=1 LIMIT 4")]);
    } elseif ($path === '/shop' && $method === 'GET') {
        $params=[]; $where="p.status='active'"; if (!empty($_GET['category'])) {$where.=' AND c.slug=?';$params[]=$_GET['category'];}
        render('listing',['title'=>'Shop','heading'=>'All products','eyebrow'=>'Originals & independent brands','intro'=>'Limited-run pieces from across the MORFINITY platform.','filters'=>query_all("SELECT * FROM categories WHERE status='active'"),'products'=>query_all("SELECT p.*,b.name brand_name FROM products p LEFT JOIN brands b ON b.id=p.brand_id LEFT JOIN categories c ON c.id=p.category_id WHERE $where ORDER BY p.created_at DESC",$params)]);
    } elseif ($path === '/originals' && $method === 'GET') {
        render('listing',['title'=>'MORFINITY Originals','heading'=>'MORFINITY Originals','eyebrow'=>'Designed in-house','intro'=>'Original ideas, made tangible by our own studio and production system.','products'=>query_all("SELECT p.*,NULL brand_name FROM products p WHERE p.status='active' AND p.brand_id IS NULL")]);
    } elseif ($path === '/collections' && $method === 'GET') {
        render('listing',['title'=>'Collections','heading'=>'Collections','intro'=>'Ideas assembled into focused releases.','products'=>query_all("SELECT p.*,b.name brand_name FROM products p LEFT JOIN brands b ON b.id=p.brand_id WHERE p.status='active' AND p.collection_id IS NOT NULL")]);
    } elseif (preg_match('#^/product/([a-z0-9-]+)$#',$path,$m) && $method==='GET') {
        $product=query_one("SELECT p.*,b.name brand_name FROM products p LEFT JOIN brands b ON b.id=p.brand_id WHERE p.slug=? AND p.status='active'",[$m[1]]); if(!$product){render('error',['title'=>'Product not found','message'=>'That product is unavailable.'],404);}else render('product',['title'=>$product['name'],'product'=>$product]);
    } elseif ($path === '/brands' && $method === 'GET') {
        render('brands',['title'=>'MORFINITY Brands','brands'=>query_all("SELECT * FROM brands WHERE status='active' ORDER BY featured DESC,name")]);
    } elseif (preg_match('#^/brands/([a-z0-9-]+)$#',$path,$m) && $method==='GET') {
        $brand=query_one("SELECT * FROM brands WHERE slug=? AND status='active'",[$m[1]]); if(!$brand){render('error',['title'=>'Brand not found','message'=>'That brand is unavailable.'],404);}else render('brand',['title'=>$brand['name'],'brand'=>$brand,'products'=>query_all("SELECT p.*,? brand_name FROM products p WHERE p.brand_id=? AND p.status='active'",[$brand['name'],$brand['id']])]);
    } elseif ($path === '/cart/add' && $method === 'POST') {
        verify_csrf(); $id=(int)($_POST['product_id']??0); $p=query_one("SELECT id,stock FROM products WHERE id=? AND status='active'",[$id]); if(!$p) throw new UserInputException('Product is unavailable.'); $qty=max(1,min((int)$p['stock'],(int)($_POST['quantity']??1))); $_SESSION['cart'][$id]=min((int)$p['stock'],($_SESSION['cart'][$id]??0)+$qty); flash('success','Added to your bag.'); redirect('/cart');
    } elseif ($path === '/cart/update' && $method === 'POST') {
        verify_csrf(); foreach(($_POST['qty']??[]) as $id=>$qty){$qty=max(0,min(99,(int)$qty));if($qty===0)unset($_SESSION['cart'][(int)$id]);else $_SESSION['cart'][(int)$id]=$qty;} flash('success','Bag updated.');redirect('/cart');
    } elseif ($path === '/cart' && $method === 'GET') {
        render('cart',['title'=>'Shopping bag','cart'=>cart_details()]);
    } elseif ($path === '/checkout' && $method === 'GET') {
        if(!cart_details()['items']) redirect('/cart'); render('form',['title'=>'Checkout','intro'=>'Submit your order request. We will confirm availability, shipping and manual payment instructions. No card is charged online.','action'=>'/checkout','submit'=>'Place order request','fields'=>checkout_fields()]);
    } elseif ($path === '/checkout' && $method === 'POST') {
        verify_csrf(); $cart=cart_details(); if(!$cart['items']) redirect('/cart'); $required=['customer_name','email','address','country']; foreach($required as $f) if(trim($_POST[$f]??'')==='') throw new UserInputException('Please complete all required checkout fields.'); if(!filter_var($_POST['email'],FILTER_VALIDATE_EMAIL))throw new UserInputException('Enter a valid email address.');
        $number='MOR-'.date('ymd').'-'.strtoupper(bin2hex(random_bytes(3))); db()->beginTransaction(); try{execute("INSERT INTO orders(order_number,customer_name,email,phone,address,city,postal_code,country,notes,subtotal,total) VALUES(?,?,?,?,?,?,?,?,?,?,?)",[$number,trim($_POST['customer_name']),strtolower(trim($_POST['email'])),trim($_POST['phone']??''),trim($_POST['address']),trim($_POST['city']??''),trim($_POST['postal_code']??''),trim($_POST['country']),trim($_POST['notes']??''),$cart['subtotal'],$cart['subtotal']]);$oid=(int)db()->lastInsertId();foreach($cart['items'] as $i)execute("INSERT INTO order_items(order_id,product_id,product_name,quantity,unit_price,line_total) VALUES(?,?,?,?,?,?)",[$oid,$i['id'],$i['name'],$i['quantity'],$i['unit_price'],$i['line_total']]);db()->commit();unset($_SESSION['cart']);redirect('/order-confirmation?ref='.urlencode($number));}catch(Throwable $e){db()->rollBack();throw $e;}
    } elseif ($path === '/order-confirmation' && $method === 'GET') {
        $order=query_one("SELECT order_number,email FROM orders WHERE order_number=?",[$_GET['ref']??'']); if(!$order)redirect('/');render('confirmation',['title'=>'Order received','order'=>$order]);
    } elseif ($path === '/launch-your-brand' && $method === 'GET') {
        render('form',['title'=>'Launch your brand','intro'=>'Tell us where the idea starts. We will review the creative, product and launch opportunity with care.','action'=>'/launch-your-brand','submit'=>'Submit application','fields'=>application_fields()]);
    } elseif ($path === '/launch-your-brand' && $method === 'POST') {
        verify_csrf(); foreach(['applicant_name','email','story'] as $f)if(trim($_POST[$f]??'')==='')throw new UserInputException('Complete all required fields.');if(!filter_var($_POST['email'],FILTER_VALIDATE_EMAIL))throw new UserInputException('Enter a valid email.');if(empty($_POST['agreement']))throw new UserInputException('You must agree to the privacy notice.');$art=validate_upload('artwork','applications',true);execute("INSERT INTO brand_applications(applicant_name,email,phone,country,brand_name,story,target_audience,preferred_style,preferred_products,artwork,social_links,budget,launch_date,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)",[trim($_POST['applicant_name']),strtolower(trim($_POST['email'])),trim($_POST['phone']??''),trim($_POST['country']??''),trim($_POST['brand_name']??''),trim($_POST['story']),trim($_POST['target_audience']??''),trim($_POST['preferred_style']??''),trim($_POST['preferred_products']??''),$art,trim($_POST['social_links']??''),trim($_POST['budget']??''),$_POST['launch_date']?:null,trim($_POST['notes']??'')]);clear_old();flash('success','Your application has been received. We will be in touch.');redirect('/launch-your-brand');
    } elseif ($path === '/contact' && $method === 'GET') {
        render('form',['title'=>'Contact','intro'=>'Questions, collaborations, production enquiries—send us a note.','action'=>'/contact','fields'=>[['name'=>'name','label'=>'Name','required'=>1],['name'=>'email','label'=>'Email','type'=>'email','required'=>1],['name'=>'subject','label'=>'Subject','full'=>1],['name'=>'message','label'=>'Message','type'=>'textarea','required'=>1,'full'=>1]]]);
    } elseif ($path === '/contact' && $method === 'POST') {
        verify_csrf();if(!filter_var($_POST['email']??'',FILTER_VALIDATE_EMAIL)||trim($_POST['message']??'')==='')throw new UserInputException('Enter a valid email and message.');execute("INSERT INTO contacts(name,email,subject,message) VALUES(?,?,?,?)",[trim($_POST['name']??''),strtolower(trim($_POST['email'])),trim($_POST['subject']??''),trim($_POST['message'])]);flash('success','Message received. Thank you.');redirect('/contact');
    } elseif ($path === '/newsletter' && $method === 'POST') {
        verify_csrf();$email=strtolower(trim($_POST['email']??''));if(!filter_var($email,FILTER_VALIDATE_EMAIL))throw new UserInputException('Enter a valid email.');execute("INSERT INTO newsletter_subscribers(email) VALUES(?) ON DUPLICATE KEY UPDATE status='active'",[$email]);flash('success','You are on the list.');redirect(validation_redirect_target());
    } elseif (handle_content($path)) {
    } elseif (str_starts_with($path,'/admin')) {
        handle_admin($path,$method);
    } else render('error',['title'=>'Page not found','message'=>'The page may have moved or never existed.'],404);
} catch (UserInputException $e) {
    set_old($_POST); flash('error', $e->getMessage()); redirect(validation_redirect_target());
} catch (Throwable $e) {
    log_exception($e);
    render('error', ['title' => 'Something went wrong', 'message' => safe_exception_message($e)], 500);
}

function checkout_fields(): array{return [['name'=>'customer_name','label'=>'Full name','required'=>1],['name'=>'email','label'=>'Email','type'=>'email','required'=>1],['name'=>'phone','label'=>'Phone'],['name'=>'country','label'=>'Country','required'=>1],['name'=>'address','label'=>'Address','required'=>1,'full'=>1],['name'=>'city','label'=>'City'],['name'=>'postal_code','label'=>'Postal code'],['name'=>'notes','label'=>'Order notes','type'=>'textarea','full'=>1]];}
function application_fields(): array{return [['name'=>'applicant_name','label'=>'Applicant name','required'=>1],['name'=>'email','label'=>'Email','type'=>'email','required'=>1],['name'=>'phone','label'=>'Phone number'],['name'=>'country','label'=>'Country'],['name'=>'brand_name','label'=>'Proposed brand name'],['name'=>'target_audience','label'=>'Target audience'],['name'=>'story','label'=>'Brand idea and story','type'=>'textarea','required'=>1,'full'=>1],['name'=>'preferred_style','label'=>'Preferred style'],['name'=>'preferred_products','label'=>'Preferred products'],['name'=>'artwork','label'=>'Existing logo or artwork','type'=>'file'],['name'=>'social_links','label'=>'Social-media links'],['name'=>'budget','label'=>'Estimated budget'],['name'=>'launch_date','label'=>'Expected launch date','type'=>'date'],['name'=>'notes','label'=>'Additional notes','type'=>'textarea','full'=>1],['name'=>'agreement','label'=>'Agreement','type'=>'checkbox','help'=>'I agree to the privacy policy and to being contacted about this application.','required'=>1,'full'=>1]];}

function handle_content(string $path): bool {
 $pages=[
 '/production'=>['MORFINITY Production','Design to dispatch.','We connect creative direction to product design, printing, quality control, packaging and fulfilment. The production system is built to grow from a first T-shirt drop into broader categories.'],
 '/how-it-works'=>['How it works','From idea to independent brand.','<h2>01 — Discover</h2><p>We start with your idea, audience and ambition.</p><h2>02 — Define</h2><p>Identity, visual system, product direction and launch scope are shaped together.</p><h2>03 — Make</h2><p>We design products and coordinate production, printing, packaging and the online shop.</p><h2>04 — Launch</h2><p>You lead promotion and community. MORFINITY provides the creative and operational foundation.</p>'],
 '/about'=>['About MORFINITY','A platform for original ideas.','MORFINITY is a parent brand, creative studio and production platform. We make our own originals and help independent founders build brands with distinct identities—each powered by shared creative and operational infrastructure.'],
 '/faq'=>['Frequently asked questions','Straight answers before we begin.','<h2>Do you only make T-shirts?</h2><p>No. T-shirts are the starting point; the system supports hoodies, accessories, art and lifestyle categories.</p><h2>Who owns an independent brand?</h2><p>Ownership and commercial terms are agreed for each project before work begins.</p><h2>Can I pay online?</h2><p>The first launch uses secure order requests. We confirm availability, shipping and payment instructions manually.</p>'],
 '/privacy'=>['Privacy policy','How we handle information.','<p><strong>Last updated: '.date('F Y').'.</strong></p><p>We collect information you submit for orders, applications, contact and newsletters. We use it only to provide requested services, administer the website, meet legal obligations and communicate with you. We do not sell personal data. Contact '.e(setting('contact_email','hello@example.com')).' for access, correction or deletion requests. Hosting and email providers may process data on our behalf under appropriate safeguards.</p>'],
 '/terms'=>['Terms and conditions','The terms for using this website.','<p>Product descriptions, prices and availability may change. An order request is not accepted until MORFINITY confirms it. Intellectual property on this site belongs to MORFINITY or the identified independent brand. Project, production and brand-launch work is governed by a separate written agreement.</p>'],
 '/returns-shipping'=>['Returns & shipping','Clear expectations for every order.','<p>Shipping cost, carrier and delivery estimate are confirmed before payment during the initial order-request launch. Contact us promptly after delivery if an item is damaged or incorrect. Final return eligibility, window and address must be configured for your selling country before launch.</p>']];
 if(!isset($pages[$path]))return false;[$title,$intro,$body]=$pages[$path];if(!str_contains($body,'<'))$body='<p>'.e($body).'</p>';render('content',compact('title','intro','body'));return true;
}

function handle_admin(string $path,string $method): void {
 if($path==='/admin/login'&&$method==='GET'){render('admin/login',['title'=>'Admin sign in']);return;}
 if($path==='/admin/login'&&$method==='POST'){verify_csrf();$a=query_one('SELECT * FROM admins WHERE email=?',[strtolower(trim($_POST['email']??''))]);if(!$a||!password_verify($_POST['password']??'',$a['password_hash'])){usleep(300000);throw new UserInputException('Invalid email or password.');}session_regenerate_id(true);$_SESSION['admin_id']=$a['id'];redirect('/admin');}
 require_admin();
 if($path==='/admin/logout'&&$method==='POST'){verify_csrf();unset($_SESSION['admin_id']);session_regenerate_id(true);redirect('/');}
 if($path==='/admin'&&$method==='GET'){render('admin/dashboard',['title'=>'Dashboard','stats'=>['Products'=>query_one('SELECT COUNT(*) n FROM products')['n'],'Orders'=>query_one('SELECT COUNT(*) n FROM orders')['n'],'Applications'=>query_one('SELECT COUNT(*) n FROM brand_applications')['n'],'Subscribers'=>query_one("SELECT COUNT(*) n FROM newsletter_subscribers WHERE status='active'")['n']],'orders'=>query_all('SELECT * FROM orders ORDER BY created_at DESC LIMIT 8')]);return;}
 if($path==='/admin/products'&&$method==='GET'){render('admin/table',['title'=>'Products','heading'=>'Products','rows'=>query_all('SELECT id,name,price,stock,status FROM products ORDER BY id DESC'),'columns'=>['name'=>'Name','price'=>'Price','stock'=>'Stock','status'=>'Status'],'newUrl'=>'/admin/products/new','editBase'=>'/admin/products/edit','deleteBase'=>'/admin/products/delete']);return;}
 if(preg_match('#^/admin/products/(new|edit(?:/(\d+))?)$#',$path,$m)&&$method==='GET'){$rec=!empty($m[2])?(query_one('SELECT * FROM products WHERE id=?',[(int)$m[2]])?:[]):[];render('admin/edit',['title'=>'Edit product','heading'=>empty($m[2])?'New product':'Edit product','record'=>$rec,'fields'=>product_admin_fields()]);return;}
 if(preg_match('#^/admin/products/(new|edit(?:/(\d+))?)$#',$path,$m)&&$method==='POST'){verify_csrf();save_product(!empty($m[2])?(int)$m[2]:null);flash('success','Product saved.');redirect('/admin/products');}
 if(preg_match('#^/admin/products/delete/(\d+)$#',$path,$m)&&$method==='POST'){verify_csrf();execute('DELETE FROM products WHERE id=?',[(int)$m[1]]);flash('success','Product deleted.');redirect('/admin/products');}
 if($path==='/admin/brands'&&$method==='GET'){render('admin/table',['title'=>'Brands','heading'=>'Brands','rows'=>query_all('SELECT id,name,tagline,status FROM brands ORDER BY id DESC'),'columns'=>['name'=>'Name','tagline'=>'Tagline','status'=>'Status'],'newUrl'=>'/admin/brands/new','editBase'=>'/admin/brands/edit','deleteBase'=>'/admin/brands/delete']);return;}
 if(preg_match('#^/admin/brands/(new|edit(?:/(\d+))?)$#',$path,$m)&&$method==='GET'){$rec=!empty($m[2])?(query_one('SELECT * FROM brands WHERE id=?',[(int)$m[2]])?:[]):[];render('admin/edit',['title'=>'Edit brand','heading'=>empty($m[2])?'New brand':'Edit brand','record'=>$rec,'fields'=>brand_admin_fields()]);return;}
 if(preg_match('#^/admin/brands/(new|edit(?:/(\d+))?)$#',$path,$m)&&$method==='POST'){verify_csrf();save_brand(!empty($m[2])?(int)$m[2]:null);flash('success','Brand saved.');redirect('/admin/brands');}
 if(preg_match('#^/admin/brands/delete/(\d+)$#',$path,$m)&&$method==='POST'){verify_csrf();execute('DELETE FROM brands WHERE id=?',[(int)$m[1]]);redirect('/admin/brands');}
 $tables=['/admin/orders'=>['Orders','SELECT id,order_number,customer_name,total,status,created_at FROM orders ORDER BY id DESC',['order_number'=>'Reference','customer_name'=>'Customer','total'=>'Total','status'=>'Status','created_at'=>'Created'],'/admin/orders/status',['pending','confirmed','processing','shipped','completed','cancelled']],'/admin/applications'=>['Brand applications','SELECT id,applicant_name,email,brand_name,status,created_at FROM brand_applications ORDER BY id DESC',['applicant_name'=>'Applicant','email'=>'Email','brand_name'=>'Brand','status'=>'Status','created_at'=>'Created'],'/admin/applications/status',['new','reviewing','accepted','declined']],'/admin/inbox'=>['Contact inbox','SELECT id,name,email,subject,status,created_at FROM contacts ORDER BY id DESC',['name'=>'Name','email'=>'Email','subject'=>'Subject','status'=>'Status','created_at'=>'Created'],'/admin/contacts/status',['new','read','replied']],'/admin/subscribers'=>['Newsletter subscribers','SELECT id,email,status,created_at FROM newsletter_subscribers ORDER BY id DESC',['email'=>'Email','status'=>'Status','created_at'=>'Subscribed'],'/admin/subscribers/status',['active','unsubscribed']]];
 if(isset($tables[$path])&&$method==='GET'){[$h,$sql,$cols,$base,$statuses]=$tables[$path];render('admin/table',['title'=>$h,'heading'=>$h,'rows'=>query_all($sql),'columns'=>$cols,'statusBase'=>$base,'statuses'=>$statuses]);return;}
 if(preg_match('#^/admin/(orders|applications|contacts|subscribers)/status/(\d+)$#',$path,$m)&&$method==='POST'){verify_csrf();$map=['orders'=>'orders','applications'=>'brand_applications','contacts'=>'contacts','subscribers'=>'newsletter_subscribers'];execute('UPDATE '.$map[$m[1]].' SET status=? WHERE id=?',[$_POST['status'],(int)$m[2]]);redirect('/admin/'.($m[1]==='contacts'?'inbox':$m[1]));}
 foreach(['categories'=>'categories','collections'=>'collections'] as $route=>$table){if($path==='/admin/'.$route&&$method==='GET'){render('admin/table',['title'=>ucfirst($route),'heading'=>ucfirst($route),'rows'=>query_all("SELECT id,name,slug,status FROM $table ORDER BY name"),'columns'=>['name'=>'Name','slug'=>'Slug','status'=>'Status'],'newUrl'=>'/admin/'.$route.'/new','editBase'=>'/admin/'.$route.'/edit','deleteBase'=>'/admin/'.$route.'/delete']);return;}if(preg_match('#^/admin/'.$route.'/(new|edit(?:/(\d+))?)$#',$path,$m)&&$method==='GET'){$rec=!empty($m[2])?(query_one("SELECT * FROM $table WHERE id=?",[(int)$m[2]])?:[]):[];render('admin/edit',['title'=>ucfirst($route),'heading'=>empty($m[2])?'New '.rtrim($route,'s'):'Edit '.rtrim($route,'s'),'record'=>$rec,'fields'=>[['name'=>'name','label'=>'Name'],['name'=>'slug','label'=>'Slug'],['name'=>'status','label'=>'Status','type'=>'select','options'=>['active'=>'Active','hidden'=>'Hidden']],['name'=>'description','label'=>'Description','type'=>'textarea','full'=>1]]]);return;}if(preg_match('#^/admin/'.$route.'/(new|edit(?:/(\d+))?)$#',$path,$m)&&$method==='POST'){verify_csrf();$id=!empty($m[2])?(int)$m[2]:null;$data=[trim($_POST['name']),slugify($_POST['slug']?:$_POST['name']),$_POST['status'],trim($_POST['description'])];if($id)execute("UPDATE $table SET name=?,slug=?,status=?,description=? WHERE id=?",[...$data,$id]);else execute("INSERT INTO $table(name,slug,status,description) VALUES(?,?,?,?)",$data);redirect('/admin/'.$route);}if(preg_match('#^/admin/'.$route.'/delete/(\d+)$#',$path,$m)&&$method==='POST'){verify_csrf();execute("DELETE FROM $table WHERE id=?",[(int)$m[1]]);redirect('/admin/'.$route);}}
 if($path==='/admin/settings'&&$method==='GET'){$rec=array_column(query_all('SELECT setting_value,setting_key FROM settings'),'setting_value','setting_key');render('admin/edit',['title'=>'Settings','heading'=>'Website settings','record'=>$rec,'fields'=>[['name'=>'site_name','label'=>'Site name'],['name'=>'contact_email','label'=>'Contact email','type'=>'email'],['name'=>'currency_symbol','label'=>'Currency symbol'],['name'=>'instagram_url','label'=>'Instagram URL'],['name'=>'tiktok_url','label'=>'TikTok URL']]]);return;}
 if($path==='/admin/settings'&&$method==='POST'){verify_csrf();foreach(['site_name','contact_email','currency_symbol','instagram_url','tiktok_url'] as $key)execute('INSERT INTO settings(setting_key,setting_value) VALUES(?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)',[$key,trim($_POST[$key]??'')]);flash('success','Settings saved.');redirect('/admin/settings');}
 render('error',['title'=>'Admin page not found','message'=>'This administration page does not exist.'],404);
}

function product_admin_fields():array{$brands=[''=>'MORFINITY Originals']+array_column(query_all('SELECT name,id FROM brands ORDER BY name'),'name','id');$cats=[''=>'None']+array_column(query_all('SELECT name,id FROM categories ORDER BY name'),'name','id');$cols=[''=>'None']+array_column(query_all('SELECT name,id FROM collections ORDER BY name'),'name','id');return [['name'=>'name','label'=>'Name'],['name'=>'slug','label'=>'Slug'],['name'=>'brand_id','label'=>'Brand','type'=>'select','options'=>$brands],['name'=>'category_id','label'=>'Category','type'=>'select','options'=>$cats],['name'=>'collection_id','label'=>'Collection','type'=>'select','options'=>$cols],['name'=>'price','label'=>'Price','type'=>'number'],['name'=>'sale_price','label'=>'Sale price','type'=>'number'],['name'=>'stock','label'=>'Stock','type'=>'number'],['name'=>'sizes','label'=>'Sizes (comma separated)'],['name'=>'colours','label'=>'Colours'],['name'=>'status','label'=>'Status','type'=>'select','options'=>['draft'=>'Draft','active'=>'Active','hidden'=>'Hidden']],['name'=>'featured','label'=>'Feature on homepage','type'=>'checkbox'],['name'=>'image_upload','label'=>'Product image','type'=>'file'],['name'=>'description','label'=>'Description','type'=>'textarea','full'=>1]];}
function brand_admin_fields():array{return [['name'=>'name','label'=>'Name'],['name'=>'slug','label'=>'Slug'],['name'=>'tagline','label'=>'Tagline'],['name'=>'accent_color','label'=>'Accent colour'],['name'=>'status','label'=>'Status','type'=>'select','options'=>['active'=>'Active','hidden'=>'Hidden']],['name'=>'featured','label'=>'Featured','type'=>'checkbox'],['name'=>'logo_upload','label'=>'Logo','type'=>'file'],['name'=>'description','label'=>'Description','type'=>'textarea','full'=>1]];}
function save_product(?int $id):void{$img=validate_upload('image_upload','products');$data=[trim($_POST['name']),slugify($_POST['slug']?:$_POST['name']),$_POST['brand_id']?:null,$_POST['category_id']?:null,$_POST['collection_id']?:null,(float)$_POST['price'],$_POST['sale_price']!==''?(float)$_POST['sale_price']:null,max(0,(int)$_POST['stock']),trim($_POST['sizes']),trim($_POST['colours']),$_POST['status'],isset($_POST['featured'])?1:0,trim($_POST['description'])];if($id){$sql='UPDATE products SET name=?,slug=?,brand_id=?,category_id=?,collection_id=?,price=?,sale_price=?,stock=?,sizes=?,colours=?,status=?,featured=?,description=?'.($img?',image=?':'').' WHERE id=?';if($img)$data[]=$img;$data[]=$id;execute($sql,$data);}else{execute('INSERT INTO products(name,slug,brand_id,category_id,collection_id,price,sale_price,stock,sizes,colours,status,featured,description,image) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[...$data,$img]);}}
function save_brand(?int $id):void{$logo=validate_upload('logo_upload','brands');$data=[trim($_POST['name']),slugify($_POST['slug']?:$_POST['name']),trim($_POST['tagline']),trim($_POST['accent_color'])?:'#191919',$_POST['status'],isset($_POST['featured'])?1:0,trim($_POST['description'])];if($id){$sql='UPDATE brands SET name=?,slug=?,tagline=?,accent_color=?,status=?,featured=?,description=?'.($logo?',logo=?':'').' WHERE id=?';if($logo)$data[]=$logo;$data[]=$id;execute($sql,$data);}else execute('INSERT INTO brands(name,slug,tagline,accent_color,status,featured,description,logo) VALUES(?,?,?,?,?,?,?,?)',[...$data,$logo]);}
